barneyseletronics/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('produto.urls')),
    path('pedido/', include('pedido.urls')),
    path('perfil/', include('perfil.urls')),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns.append(
        path('__debug__/', include('debug_toolbar.urls')),
    )

pedido/urls.py
from django.urls import path
from pedido.views import Pagar, FecharPedido, Detalhe

urlpatterns = [
    path('pagar/', Pagar.as_view(), name='pagar'),
    path('fecharpedido/', FecharPedido.as_view(), name='fecharpedido'),
    path('<slug>', Detalhe.as_view(), name='detalhe'),
]

perfil/urls.py
from django.urls import path
from perfil.views import CriarPerfil, Update, Login, Logout

urlpatterns = [
    path('criar_perfil/', CriarPerfil.as_view(), name='criar_perfil'),
    path('update/', Update.as_view(), name='update'),
    path('login/', Login.as_view(), name='login'),
    path('logout/', Logout.as_view(), name='logout'),
]

produto/urls.py
from django.urls import path
from produto.views import home
from produto.views import produtoDetalhe, add_carrinho, rm_carrinho, carrinho, finalizar

urlpatterns = [
    path('', home.as_view(), name='home'),
    path('<slug>', produtoDetalhe.as_view(), name='detalhe'),
    path('add_carrinho/', add_carrinho.as_view(), name='add_carrinho'),
    path('rm_carrinho/', rm_carrinho.as_view(), name='rm_carrinho'),
    path('carrinho/', carrinho.as_view(), name='carrinho'),
    path('finalizar/', finalizar.as_view(), name='finalizar'),
]

pedido/models.py
from django.db import models
from django.contrib.auth.models import User


class Status(models.Model):
    status = models.CharField(max_length=50)

    def __str__(self):
        return self.status

    class Meta:
        verbose_name = 'Status'
        verbose_name_plural = 'Status'

class Pedido(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    total = models.FloatField()
    status = models.ForeignKey(Status, on_delete=models.CASCADE)

    def __str__(self):
        return f'Pedido N. {self.pk}'

class ItemPedido(models.Model):
    pedido = models.ForeignKey(Pedido, on_delete=models.CASCADE)
    produto = models.CharField(max_length=255)
    produto_id = models.PositiveIntegerField()
    variacao = models.CharField(max_length=255)
    variacao_id = models.PositiveIntegerField()
    preco = models.FloatField()
    preco_promocional = models.FloatField()
    quantidade = models.PositiveIntegerField()
    imagem = models.CharField(max_length=2000)

    def __str__(self):
        return f'Item do {self.pedido}'

    class Meta:
        verbose_name = 'Item do Pedido'
        verbose_name_plural = 'Itens do Pedido'

perfil/models.py
from django.contrib.auth.models import User
from django.db import models

class Estado(models.Model):
    estado = models.CharField(max_length=50)

    def __str__(self):
        return self.estado

class PerfilUsuario(models.Model):
    usuario = models.ForeignKey(User, on_delete=models.CASCADE)
    idade = models.IntegerField()
    data = models.DateTimeField()
    cpf = models.CharField(max_length=11)
    endereco = models.CharField(max_length=50)
    numero = models.CharField(max_length=5)
    complemento = models.CharField(max_length=30)
    bairro = models.CharField(max_length=30)
    cep = models.CharField(max_length=8)
    cidade = models.CharField(max_length=30)
    estado = models.ForeignKey(Estado, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.usuario}'

    def clean(self):
        pass

    class Meta:
        verbose_name = 'Perfil'
        verbose_name_plural = 'Perfis'

produto/models.py
import os.path
from PIL import Image
from django.conf import settings
from django.db import models
from django.utils.safestring import mark_safe
from django.utils.text import slugify


class Categoria(models.Model):
    categoria = models.CharField(max_length=50)

    def __str__(self):
        return self.categoria

class Produto(models.Model):
    nome = models.CharField(max_length=50)
    descricao_curta = models.TextField(max_length=255)
    descricao_longa = models.TextField()
    img = models.ImageField(upload_to='post_img')
    slug = models.SlugField(unique=True, blank=True, null=True)
    preco = models.FloatField(default=0)
    preco_promocional = models.FloatField(default=0)
    categoria = models.ForeignKey(Categoria, on_delete=models.CASCADE)
    ativo = models.BooleanField(default=True)


    # método para redimensionar as imagens
    @staticmethod
    def resize_image(img, new_width=800):
        img_full_path = os.path.join(settings.MEDIA_ROOT, img.name)
        img_pil = Image.open(img_full_path)
        original_width, original_height = img_pil.size

        if original_width <= new_width:
            print('Retornando, largura original menor que nova largura')
            img_pil.close()
            return

        new_heigth = round((new_width * original_height)/original_width)

        new_img = img_pil.resize((new_width, new_heigth), Image.LANCZOS)
        new_img.save(
            img_full_path,
            optimize=True,
            quality=50,
        )

    def save(self, *args, **kwargs):
        if not self.slug:
            slug = f'{slugify(self.nome)}'
            self.slug = slug


        super().save(*args, **kwargs)

        max_image_size = 800

        if self.img:
            self.resize_image(self.img, max_image_size)

    @mark_safe
    def icone(self):
        return f'<img width="30px" src="media/{self.img.url}">'

    def __str__(self):
        return self.nome

    class Meta():
        verbose_name = 'Produto'
        verbose_name_plural = 'Produtos'


class Variacao(models.Model):
    produto = models.ForeignKey(Produto, on_delete=models.CASCADE)
    nome = models.CharField(max_length=50, blank=True, null=True)
    preco = models.FloatField()
    preco_promocional = models.FloatField(default=0)
    estoque = models.PositiveIntegerField(default=1)

    def __str__(self):
        return self.nome or self.produto.nome

    class Meta():
        verbose_name = 'Variação'
        verbose_name_plural = 'Variações'

pedido/views.py
from django.views.generic.list import ListView
from django.views import View
from django.shortcuts import render

class Pagar(ListView):
    def get(self, request, *args, **kwargs):
        return render(request, 'pagar.html')

class FecharPedido(View):
    def get(self, request, *args, **kwargs):
        return render(request, 'finalizar.html')

class Detalhe(View):
    pass

perfil/views.py
from django.views.generic.list import ListView
from django.views import View
from django.shortcuts import render

class CriarPerfil(ListView):
    def get(self, request, *args, **kwargs):
        return render(request, 'criar_perfil.html')

class Update(View):
    def get(self, request, *args, **kwargs):
        return render(request, 'update.html')

class Login(View):
    def get(self, request, *args, **kwargs):
        return render(request, 'login.html')

class Logout(View):
    def get(self, request, *args, **kwargs):
        return render(request, 'logout.html')

produto/views.py
from django.shortcuts import render
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views import View
from . import models

class home(ListView):
    model = models.Produto
    template_name = 'home.html'
    context_object_name = 'produtos'
    paginate_by = 9

class produtoDetalhe(DetailView):
    model = models.Produto
    template_name = 'detalhe.html'
    context_object_name = 'produto'
    slug_url_kwarg = 'slug'

class add_carrinho(View):
    pass

class rm_carrinho(View):
    def get(self, request, *args, **kwargs):
        return render(request, 'rm_carrinho.html')

class carrinho(View):
    def get(self, request, *args, **kwargs):
        return render(request, 'carrinho.html')

class finalizar(View):
    def get(self, request, *args, **kwargs):
        return render(request, 'finalizar.html')

pedido/templates/finalizar.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Finalizar</title>
</head>
<body>
    <h1>Finalize a compra aqui</h1>
</body>
</html>

pedido/templates/pagar.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Pagamento</title>
</head>
<body>
    <h1>pagina de pagamento</h1>
</body>
</html>

perfil/templates/criar_perfil.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Cadastro</title>
</head>
<body>
    <h1>Página de cadastro</h1>
</body>
</html>

perfil/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>login</title>
</head>
<body>
    <h1>Faça seu login</h1>
</body>
</html>

perfil/templates/logout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>logout</title>
</head>
<body>
    <h1>Quando você sair da conta cairá aqui</h1>
</body>
</html>

perfil/templates/update.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Update</title>
</head>
<body>
    <h1>Atualize seus dados</h1>
</body>
</html>

produto/templates/add_carrinho.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

produto/templates/carrinho.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

produto/templates/detalhe.html
{% extends 'base.html' %}

{% block conteudo %}
                <div class="row">
                    <div class="col-lg">
                        <div class="row no-gutters">
                            <div class="col-lg-12">
                                {% if produto.img %}
                                <img class="img-fluid" src="{{ produto.img.url }}">
                                {% endif %}
                            </div>
                        </div>
                    </div>
                    <div class="col-lg">
                        <div class="mt-4 mt-lg-0">
                            <h1 class="h2">{{ produto.nome}}</h1>
                            <p class="lead">{{ produto.descricao_curta }}</p>
                            <p class="lead">
                                {% if produto.preco_promocional %}
                                <span id="variation-preco-promocional" class="lead product-price">
                                    R$ {{ produto.preco_promocional }}</span>
                                <span id="variation-preco" class="lead product-old-price text-muted">
                                    R$ {{ produto.preco }}</span>
                                {% else %}
                                <span id="variation-preco" class="lead product-old-price text-muted">
                                    R$ {{ produto.preco }}</span>
                                {% endif %}
                            </p>

                            <form action="/addtocart/" id="form-add-to-cart">
                                <div class="form-group">
                                    <select id="select-variacoes" name="vid" class="form-control form-control-lg">
                                        {% for variacao in produto.variacao_set.all %}

                                        <option data-preco="R$ {{ variacao.preco }}"
                                            data-preco-promocional="R$ {{ variacao.preco_promocional }}"
                                            value="{{ variacao.id }}">{{ variacao }}
                                        </option>
                                        {% endfor %}
                                    </select>
                                </div>

                                <div class="text-left">
                                    <button type="submit" class="btn btn-primary btn-lg btn-block">
                                        <i class="fa fa-shopping-cart" aria-hidden="true"></i>
                                        Adicionar ao carrinho
                                    </button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
<div class="row">
    <div class="col-lg-12">
        <div class="mt-5 mb-5">
            <h2 class="text-center">{{ produto.nome }}</h2>
            {{ produto.descricao_longa }}
        </div>

    </div>
</div>

{% endblock %}

produto/templates/finalizar.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Finalizar</title>
</head>
<body>
    <h1>Finalize aqui seu pedido</h1>
</body>
</html>

produto/templates/home.html
{% extends 'base.html' %}

{% block conteudo %}

        <div class="row">
            <div class="col-lg-12">
                <div class="card-columns">
                    {% for produto in produtos %}
                    <div class="card">
                        {% if produto.img %}
                        <a href="{{ produto.slug }}">
                        <img class="card-img-top" src="{{ produto.img.url }}" alt={{ produto.nome }}>
                        </a>
                        {% endif %}
                        <div class="card-body">
                            <h5 class="card-title">{{ produto.nome }}</h5>
                            <p class="card-text">{{ produto.descricao_curta }}</p>
                            <div class="container product-price-block text-center">

                                {% if produto.preco_promocional %}
                                    <span class="product-price">
                                        R$ {{ produto.preco_promocional }}
                                    </span>
                                    <span class="product-old-price text-muted">
                                        R$ {{ produto.preco }}
                                    </span>
                                {% else %}
                                    <span class="product-old-price text-muted">
                                        R$ {{ produto.preco }}
                                    </span>
                                {% endif %}
                            </div>
                        </div>
                        <div class="card-footer bg-transparent border-top-light-custom text-center">
                            <a href="{{ produto.slug }}" class="btn btn-primary btn-sm m-1 btn-block">
                                <i class="fa fa-shopping-cart" aria-hidden="true"></i>
                                Comprar
                            </a>
                        </div>
                    </div>
                    {% endfor %}
                </div>
            </div>
        </div>

<div class="row mt-5">
    <div class="col">
        {% include 'parciais/_pagination.html' %}
    </div>
</div>

{% endblock %}

produto/templates/rm_carrinho.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

templates/base.html
<!doctype html>
<html lang="pt-br">

<head>
    {% include 'parciais/_head.html' %}
    <title>{% block titulo %}{% endblock %}</title>
</head>

<body>
    {% include 'parciais/_nav.html' %}
    <main class="container mt-4 mb-4">
        {% block conteudo %}{% endblock %}
    </main>

{% include 'parciais/_footer.html' %}
</body>

</html>

templates/parciais/_footer.html
{% load static %}
<footer class="container-fluid bg-primary">
        <div class="container text-light">
            <div class="row">
                <div class="col">
                    <div class="p-1">
                        <span class="align-middle p-1">Feito com Django</span>
                    </div>
                </div>
                <div class="col">
                    <div class="p-1 text-right">
                        <span class="align-middle p-1">Por Luiz Otávio</span>
                    </div>
                </div>
            </div>
        </div>
    </footer>

    <script src="{% static 'assets/bootstrap/js/jquery-3.2.1.slim.min.js' %}"></script>
    <script src="{% static 'assets/bootstrap/js/popper.min.js' %}"></script>
    <script src="{% static 'assets/bootstrap/js/bootstrap.min.js' %}"></script>
    <script defer src="{% static 'assets/font-awesome/js/all.js' %}"></script>
    <script src="{% static 'assets/custom/js/scripts.js' %}"></script>

templates/parciais/_head.html
{% load static %}
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

<link rel="stylesheet" href={% static "assets/bootstrap/css/bootstrap.css" %}>
<link rel="stylesheet" href={% static "assets/custom/css/style.css" %}>

templates/parciais/_messages.html
{% if messages %}
    <br>
    {% for message in messages %}
        <div class="alert {{ message.tags }}" role="alert">
            {{ message }}
        </div>
    {% endfor %}
{% endif %}

templates/parciais/_nav.html
<nav class="navbar navbar-dark bg-primary navbar-expand-lg">
        <a class="navbar-brand" href="index.html">Navbar</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Link</a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                        data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Dropdown
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item" href="#">Action</a>
                        <a class="dropdown-item" href="#">Another action</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="#">Something else here</a>
                    </div>
                </li>
                <li class="nav-item">
                    <a class="nav-link disabled" href="#">Disabled</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link nav-cart-link active" href="#">
                        <span class="nav-cart-text mr-1">
                            Carrinho
                        </span>
                        <span class="nav-cart-count mr-1">
                            <strong>109x</strong>
                        </span>
                        <span class="nav-cart-icon mr-2">
                            <i class="fas fa-shopping-cart"></i>
                        </span>
                    </a>
                </li>
            </ul>
            <form class="form-inline my-2 my-lg-0">
                <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
                <button class="btn btn-secondary my-2 my-sm-0" type="submit">Search</button>
            </form>
        </div>
    </nav>

templates/parciais/_pagination.html
{% if is_paginated %}
<div class="pagination">
    <ul class="pagination">
        {% if page_obj.has_previous %}
        <li class="page-item">
            <a class="page-link" href="?page=1">&laquo;</a>
        </li>
        <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.previous_page_number }}">&lsaquo;</a>
        </li>
        {% endif %}

        {% for num in page_obj.paginator.page_range %}

        {% if page_obj.number == num %}
        <li class="page-item active">
            <a class="page-link" href="?page={{ num }}">{{ num }}</a>
        </li>
        {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
        <li class="page-item">
            <a class="page-link" href="?page={{ num }}">{{ num }}</a>
        </li>
        {% endif %}

        {% endfor %}

        {% if page_obj.has_next %}
        <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.next_page_number }}">&rsaquo;</a>
        </li>
        <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">&raquo;</a>
        </li>
        {% endif %}
    </ul>
</div>
{% endif %}